### ISSUE TITLE
有抓取的过程但输出的是空文件

### ISSUE THREAD

**Issue by TaikooS** [LockeKK/weibo_backup#1]
![image](https://user-images.githubusercontent.com/12044679/71050247-a4f05b00-217f-11ea-868f-ee7aa0de5d8c.png)
![image](https://user-images.githubusercontent.com/12044679/71050275-b9345800-217f-11ea-84b3-f4bd45c24b6a.png)

**Comment by LockeKK** [comment]
I used it quite long time ago and worked quite good.
Weibo might chanced something. Not sure how could I help you.

**Comment by TaikooS** [comment]
那…没事了，估计就算我照着原来的方法做一遍也弄不了，毕竟两年了。

Thanks anyway.
